// Header generated by RemObjects Elements for Cocoa 

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#import <RemObjects.Elements.Linq.h>
#import <objc/NSObject.h>
#import <Foundation/Foundation.h>
#import <objc/objc.h>
#import <dispatch/queue.h>
#import <dispatch/object.h>

@class ArrayUtils;
@class NSMutableArray;
@class NSMutableDictionary;
@class NSMutableSet;
@class NSSet;
@protocol IEquatable;
@protocol IComparable;
@class Tuple1;
@class Tuple2;
@class Tuple3;
@class Tuple4;
@class Tuple5;
@class Tuple6;
@class Tuple7;
@class Tuple8;
@class Tuple;
@class ToffeeErrorException;
@class NSDictionary;
@class __ElementsAttribute;
@class __ElementsAttributeUsageAttribute;
@class __ElementsBoxedStruct;
@class __ElementsBoxedChar;
@class __ElementsBoxedAnsiChar;
@protocol IOxygeneFuture;
@protocol IOxygeneFuture1;
@class __Oxygene_Future;
@class __Oxygene_Future_Helper;
@protocol INSFastEnumeration;
@class __Toffee_Linq_Helpers;
@class __ElementsTask;
@class __ElementsTask1;
@class __ElementsTaskCompletionSource;
@protocol __ElementsIAwaitCompletion;
@protocol IThreadSyncHelper;
@class __ElementsDefaultThreadSyncHelper;
@class NSArray;
@class NSCountedSet;
@class RemObjects_Elements_Linq__Extensions;

typedef enum AttributeTargets: int32_t {
    AttributeTargets_Class = 4,
    AttributeTargets_Constructor = 32,
    AttributeTargets_Method = 64,
    AttributeTargets_Property = 128,
    AttributeTargets_Field = 256,
    AttributeTargets_Event = 512,
    AttributeTargets_Interface = 1024,
    AttributeTargets_Parameter = 2048,
    AttributeTargets_ReturnValue = 8192
  } AttributeTargets;

typedef struct ElementsTypeMetadata ElementsTypeMetadata;
typedef struct ElementsEventsData ElementsEventsData;
typedef struct ElementsEventData ElementsEventData;
typedef struct ElementsFieldsData ElementsFieldsData;
typedef struct ElementsFieldData ElementsFieldData;
typedef struct <>c__DisplayClass0 <>c__DisplayClass0;
typedef struct <>c__DisplayClass1 <>c__DisplayClass1;
typedef enum __Elements_ProtoReadType: int32_t {
    __Elements_ProtoReadType_varint = 0,
    __Elements_ProtoReadType_b64 = 1,
    __Elements_ProtoReadType_length = 2,
    __Elements_ProtoReadType_message = 3,
    __Elements_ProtoReadType_b32 = 5,
    __Elements_ProtoReadType_startgroup = 4,
    __Elements_ProtoReadType_endgroup = 6
  } __Elements_ProtoReadType;

typedef void(^NSSetEnumerateBlock)(id obj, BOOL * stop);
typedef BOOL(^NSSetTestBlock)(id obj, BOOL * stop);
typedef void(^NSDictionaryEnumerateBlock)(id key, id obj, BOOL * stop);
typedef BOOL(^NSDictionaryTestBlock)(id key, id obj, BOOL * stop);
typedef void(*__ElementsBoxedStructDestructor)(void * o);
typedef id(^__Oxygene_Block)();
typedef BOOL(^PredicateBlock)(id_Nonnull  aItem);
typedef id(^IDBlock)(id_Nonnull  aItem);
typedef void(^TaskBlock)();
typedef void(^NSArrayEnumerateBlock)(id obj, NSUInteger idx, BOOL * stop);
typedef BOOL(^NSArrayTestBlock)(id obj, NSUInteger idx, BOOL * stop);
typedef NSInteger(*NSArraySortMethod)(id obj1, id obj, void * context);
typedef RemObjects.Elements.System.Attribute Attribute
typedef RemObjects.Elements.System.AttributeUsageAttribute AttributeUsageAttribute
typedef RemObjects.Elements.System.TaskCompletionSource TaskCompletionSource
typedef RemObjects.Elements.System.Task Task
typedef RemObjects.Elements.System.Task1 Task1
@protocol IOxygeneFuture
- (void)wait:(BOOL)aRaise;

@property (readonly,assign) BOOL done;
@property (readonly,assign) BOOL started;
@property (readonly,strong) id value;
@property (readonly,strong) NSException *exception;
@end

@protocol __ElementsIAwaitCompletion
- (void)moveNext:(NSObject *)aState;
@end

@protocol IThreadSyncHelper
- (dispatch_queue_t)GetThreadContext;
- (void)SyncBack:(dispatch_queue_t)aContext :(dispatch_block_t)aAction;
@end

@interface ArrayUtils: NSObject

+ (id<NSFastEnumeration>)idArrayToSequence:(id * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)stringToSequence:(NSString *)val;
+ (/* mapped */ id<NSFastEnumeration>)genericArrayToSequence:(id * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)charArrayToSequence:(char * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)wcharArrayToSequence:(wchar_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)boolArrayToSequence:(BOOL * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)byteArrayToSequence:(uint8_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)sbyteArrayToSequence:(int8_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)int16ArrayToSequence:(int16_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)uint16ArrayToSequence:(uint16_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)int32ArrayToSequence:(int32_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)uint32ArrayToSequence:(uint32_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)int64ArrayToSequence:(int64_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)uint64ArrayToSequence:(uint64_t * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)singleArrayToSequence:(float * /* dynamicarray */)val;
+ (/* mapped */ id<NSFastEnumeration>)doubleArrayToSequence:(double * /* dynamicarray */)val;

@end

@interface Tuple: NSObject

+ (/* mapped */ NSArray *)New:(id)aItem1;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3 :(id)aItem4;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3 :(id)aItem4 :(id)aItem5;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3 :(id)aItem4 :(id)aItem5 :(id)aItem6;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3 :(id)aItem4 :(id)aItem5 :(id)aItem6 :(id)aItem7;
+ (/* mapped */ NSArray *)New:(id)aItem1 :(id)aItem2 :(id)aItem3 :(id)aItem4 :(id)aItem5 :(id)aItem6 :(id)aItem7 :(id)aItem8;

@end

@interface ToffeeErrorException: NSException

- (id_Nonnull )initWithError:(NSError *_Nonnull )error;

@property (nonnull,readonly,strong) NSError *error;

@end

@interface __ElementsAttribute: NSObject
@end

@interface __ElementsAttributeUsageAttribute: __ElementsAttribute

- (id)init:(AttributeTargets)aValidOn;

@property (readonly,assign) AttributeTargets ValidOn;

@end

struct ElementsTypeMetadata {
  intptr_t Size;
  void *CustomAttributes;
  void *PropertyAttributes;
  void *FieldAttributes;
  void *StaticFieldAttributes;
  void *EventAttributes;
  ElementsEventsData *Events;
  ElementsFieldsData *StaticFields;

};

struct ElementsEventsData {
  intptr_t Count;
  intptr_t ElementSize;
  ElementsEventData [1] Data;

};

struct ElementsEventData {
  char *Name;
  SEL Add;
  SEL Remove;
  SEL Raise;

};

struct ElementsFieldsData {
  intptr_t Count;
  intptr_t ElementSize;
  ElementsFieldData [1] Data;

};

struct ElementsFieldData {
  char *Name;
  void *FieldData;
  char *FieldSignature;

};

@interface __ElementsBoxedStruct: NSObject

- (id)init:(void *)aValue :(__ElementsBoxedStructDestructor)aDtor;
- (void)dealloc;
- (NSString *)description;
+ (__ElementsBoxedStruct *)boxedStructWithValue:(void *)aValue :(__ElementsBoxedStructDestructor)aDtor;
+ (void *)valueForStruct:(NSObject *)aStruct :(__ElementsBoxedStructDestructor)aDtor;
- (BOOL)isEqual:(id)object;
- (BOOL)isEqualTo:(id)object;
- (id_Nonnull )copyWithZone:(NSZone *)zone;
- (void)encodeWithCoder:(NSCoder *_Nonnull )aCoder;
- (instancetype)initWithCoder:(NSCoder *_Nonnull )aDecoder;

@property (readonly,assign) __ElementsBoxedStructDestructor Dtor;
@property (readonly,assign) void *Value;

@end

@interface __ElementsBoxedChar: NSObject <NSCopying, NSCoding>

- (id)initWithChar:(wchar_t)aChar;
+ (__ElementsBoxedChar *)boxedCharWithChar:(wchar_t)aChar;
- (NSString *)description;
+ (NSNumber *)op_Implicit:(__ElementsBoxedChar *)aValue;
+ (wchar_t)op_Implicit:(__ElementsBoxedChar *)aValue;
- (BOOL)isEqual:(id)object;
- (BOOL)isEqualTo:(id)object;
- (BOOL)isGreaterThan:(id)object;
- (BOOL)isGreaterThanOrEqualTo:(id)object;
- (BOOL)isLessThan:(id)object;
- (BOOL)isLessThanOrEqualTo:(id)object;
- (id_Nonnull )copyWithZone:(NSZone *)zone;
- (void)encodeWithCoder:(NSCoder *_Nonnull )aCoder;
- (instancetype)initWithCoder:(NSCoder *_Nonnull )aDecoder;

@property (readonly,assign) wchar_t charValue;
@property (readonly,strong) NSString *stringValue;

@end

@interface __ElementsBoxedAnsiChar: NSObject <NSCopying, NSCoding>

- (id)initWithAnsiChar:(char)aAnsiChar;
+ (__ElementsBoxedAnsiChar *)boxedAnsiCharWithAnsiChar:(char)aAnsiChar;
- (NSString *)description;
+ (NSNumber *)op_Implicit:(__ElementsBoxedAnsiChar *)aValue;
+ (char)op_Implicit:(__ElementsBoxedAnsiChar *)aValue;
- (BOOL)isEqual:(id)object;
- (BOOL)isEqualTo:(id)object;
- (BOOL)isGreaterThan:(id)object;
- (BOOL)isGreaterThanOrEqualTo:(id)object;
- (BOOL)isLessThan:(id)object;
- (BOOL)isLessThanOrEqualTo:(id)object;
- (id_Nonnull )copyWithZone:(NSZone *)zone;
- (void)encodeWithCoder:(NSCoder *_Nonnull )aCoder;
- (instancetype)initWithCoder:(NSCoder *_Nonnull )aDecoder;

@property (readonly,assign) char ansiCharValue;
@property (readonly,strong) NSString *stringValue;

@end

@interface __Oxygene_Future: NSObject <IOxygeneFuture>

- (id)init:(__Oxygene_Block)aBlock;
- (void)startAsync;
- (void)wait:(BOOL)aRaise;

@property (readonly,assign) BOOL done;
@property (readonly,strong) NSException *exception;
@property (readonly,assign) BOOL started;
@property (readonly,strong) id value;

@end

struct <>c__DisplayClass0 {
  id <Execute>b__0;
  void (^)() aFuture;

};

struct <>c__DisplayClass1 {
  id <ExecuteAsync>b__0;
  void (^)() aFuture;

};

@interface __Toffee_Linq_Helpers: NSObject

+ (/* mapped */ id<NSFastEnumeration>_Nonnull )ForHelper:(int32_t)aStart :(int32_t)aEnd :(int32_t)aStep :(BOOL)aBackward :(ForSelector)aMethod;

@end

@interface __ElementsTask: NSObject

- (id)init:(TaskBlock)aIn :(NSObject *)aState;
- (__ElementsTask *)ContinueWith:(void (^)(__ElementsTask * aTask))aAction :(NSObject *)aState;
- (__ElementsTask1 *)ContinueWith:(id (^)(__ElementsTask * aTask))aAction :(NSObject *)aState;
+ (__ElementsTask *)Run:(TaskBlock)aIn;
+ (__ElementsTask1 *)Run:(TaskBlockGen)aIn;
- (BOOL)Await:(id<__ElementsIAwaitCompletion>)aCompletion;
- (void)Wait;
- (BOOL)Wait:(int32_t)aTimeoutMSec;
- (void)Start:(dispatch_queue_t)aScheduler;
+ (id<IThreadSyncHelper>)ThreadSyncHelper;
+ (void)setThreadSyncHelper:(id<IThreadSyncHelper>)value;

@property (readonly,strong) NSException *Exception;
@property (readonly,strong) NSObject *AsyncState;
@property (readonly,assign) BOOL IsFaulted;
@property (readonly,assign) BOOL IsCompleted;

@end

@interface __ElementsDefaultThreadSyncHelper: NSObject <IThreadSyncHelper>

- (void)SyncBack:(dispatch_queue_t)aContext :(dispatch_block_t)aAction;
- (dispatch_queue_t)GetThreadContext;

@end

@interface RemObjects_Elements_Linq__Extensions: NSObject

+ (id<NSFastEnumeration>_Nonnull )Where:(id<NSFastEnumeration>)self :(PredicateBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Where:(/* mapped */ id<NSFastEnumeration>)self :(BOOL (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (BOOL)Any:(id<NSFastEnumeration>)self :(PredicateBlock_Nonnull )aBlock;
+ (BOOL)Any:(id<NSFastEnumeration>)self;
+ (BOOL)Any:(/* mapped */ id<NSFastEnumeration>)self :(BOOL (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (BOOL)Any:(/* mapped */ id<NSFastEnumeration>)self;
+ (id<NSFastEnumeration>_Nonnull )Take:(id<NSFastEnumeration>)self :(NSInteger)aCount;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Take:(/* mapped */ id<NSFastEnumeration>)self :(NSInteger)aCount;
+ (id<NSFastEnumeration>_Nonnull )Skip:(id<NSFastEnumeration>)self :(NSInteger)aCount;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Skip:(/* mapped */ id<NSFastEnumeration>)self :(NSInteger)aCount;
+ (id<NSFastEnumeration>_Nonnull )TakeWhile:(id<NSFastEnumeration>)self :(PredicateBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )TakeWhile:(/* mapped */ id<NSFastEnumeration>)self :(BOOL (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (id<NSFastEnumeration>_Nonnull )SkipWhile:(id<NSFastEnumeration>)self :(PredicateBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )SkipWhile:(/* mapped */ id<NSFastEnumeration>)self :(BOOL (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (id<NSFastEnumeration>_Nonnull )OrderBy:(id<NSFastEnumeration>)self :(IDBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )OrderBy:(/* mapped */ id<NSFastEnumeration>)self :(id (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (id<NSFastEnumeration>_Nonnull )orderBy:(id<NSFastEnumeration>)self :(id (^)(id aItem)_Nonnull )aBlock comparator:(NSComparator)aComparator;
+ (id<NSFastEnumeration>_Nonnull )OrderByDescending:(id<NSFastEnumeration>)self :(IDBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )OrderByDescending:(/* mapped */ id<NSFastEnumeration>)self :(id (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (id<NSFastEnumeration>_Nonnull )Select:(id<NSFastEnumeration>)self :(IDBlock_Nonnull )aBlock;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Select:(/* mapped */ id<NSFastEnumeration>)self :(id (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (id<NSFastEnumeration>_Nonnull )Concat:(id<NSFastEnumeration>)self :(id<NSFastEnumeration>_Nonnull )aSecond;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Concat:(/* mapped */ id<NSFastEnumeration>)self :(/* mapped */ id<NSFastEnumeration>_Nonnull )aSecond;
+ (id<NSFastEnumeration>_Nonnull )Reverse:(id<NSFastEnumeration>)self;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Reverse:(/* mapped */ id<NSFastEnumeration>)self;
+ (id<NSFastEnumeration>_Nonnull )Distinct:(id<NSFastEnumeration>)self :(NSComparator)aComparator;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Distinct:(/* mapped */ id<NSFastEnumeration>)self :(NSComparator)aComparator;
+ (id<NSFastEnumeration>_Nonnull )Intersect:(id<NSFastEnumeration>)self :(id<NSFastEnumeration>_Nonnull )aSecond :(NSComparator)aComparator;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Intersect:(/* mapped */ id<NSFastEnumeration>)self :(id<NSFastEnumeration>_Nonnull )aSecond :(NSComparator)aComparator;
+ (id<NSFastEnumeration>_Nonnull )Except:(id<NSFastEnumeration>)self :(id<NSFastEnumeration>_Nonnull )aSecond :(NSComparator)aComparator;
+ (/* mapped */ id<NSFastEnumeration>_Nonnull )Except:(/* mapped */ id<NSFastEnumeration>)self :(id<NSFastEnumeration>_Nonnull )aSecond :(NSComparator)aComparator;
+ (id)FirstOrDefault:(id<NSFastEnumeration>)self;
+ (id)FirstOrDefault:(id<NSFastEnumeration>)self :(PredicateBlock_Nonnull )aBlock;
+ (id)FirstOrDefault:(/* mapped */ id<NSFastEnumeration>)self;
+ (id)FirstOrDefault:(/* mapped */ id<NSFastEnumeration>)self :(BOOL (^)(id_Nonnull  aItem)_Nonnull )aBlock;
+ (NSInteger)Count:(id<NSFastEnumeration>)self;
+ (NSInteger)Count:(/* mapped */ id<NSFastEnumeration>)self;
+ (NSArray *_Nonnull )array:(id<NSFastEnumeration>)self;
+ (NSArray *_Nonnull )array:(/* mapped */ id<NSFastEnumeration>)self;
+ (NSDictionary *_Nonnull )dictionary:(id<NSFastEnumeration>)self :(IDBlock)aKeyBlock :(IDBlock)aValueBlock;
+ (NSDictionary *_Nonnull )dictionary:(/* mapped */ id<NSFastEnumeration>)self :(id (^)(id aItem))aKeyBlock :(id (^)(id aItem))aValueBlock;

@end


// Globals 

extern BOOL __ElementsClassLockEnter(intptr_t*x);

extern void __ElementsClassLockExit(intptr_t*x);

extern NSString *__ElementsReadLine(void );

extern ToffeeErrorException *_Nonnull  __ElementsCreateExceptionWithError(NSError *_Nonnull  error);

extern void __ElementsWillThrowError(NSError *_Nonnull  error);

extern BOOL CocoaVersionAtLeast(int32_t aMaj, int32_t aMin, int32_t aRev);

extern NSString *CocoaVersionString(void );

extern int32_t [3] CocoaVersion(void );

extern NSString *CocoaPlatform(void );

extern BOOL CocoaPlatformIs(NSString *s);

extern BOOL __ElementsCocoaVersionAtLeast(int32_t aMaj, int32_t aMin, int32_t aRev);

extern NSString *__ElementsCocoaVersionString(void );

extern int32_t [3] __ElementsCocoaVersion(void );

extern NSString *__ElementsCocoaPlatform(void );

extern BOOL __ElementsCocoaPlatformIs(NSString *s);

extern /* mapped */ NSArray *__ElementsReadAttributes(uint8_t **aAttributesPtr, int32_t aTargetParameter, Class aTypeFilter);

extern __ElementsAttribute *__ElementsReadAttribute(uint8_t *aAttributesPtr, uint8_t *aEnd, int32_t aTargetParameter, Class aTypeFilter);

extern uint8_t *__ElementsGetAttributesBlockForFunction(void *aMethod);

extern uint8_t *__ElementsGetAttributesBlockForMethod(Class aClass, BOOL aInstance, SEL aSel);

extern ElementsTypeMetadata *GetClassMetadata(Class aClass);

extern /* mapped */ NSArray *GetAttributesForType(Class aClass, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForFunction(void *aMethod, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForFunctionResult(void *aMethod, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForFunctionParameter(void *aMethod, Class aTypeFilter, int32_t aIndex);

extern /* mapped */ NSArray *GetAttributesForMethod(Class aClass, BOOL aInstance, SEL aSel, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForMethodResult(Class aClass, BOOL aInstance, SEL aSel, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForMethodParameter(Class aClass, BOOL aInstance, SEL aSel, Class aTypeFilter, int32_t aIndex);

extern /* mapped */ NSArray *GetAttributesForProperty(Class aClass, int32_t aIndexInList, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForEvent(Class aClass, int32_t aIndexInList, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForField(Class aClass, int32_t aIndexInList, Class aTypeFilter);

extern /* mapped */ NSArray *GetAttributesForStaticField(Class aClass, int32_t aIndexInList, Class aTypeFilter);

extern BOOL __Elements_ProtoReadHeader(uint8_t **aSelf, int32_t*aKey, __Elements_ProtoReadType*aType);

extern int64_t __Elements_ProtoReadVarInt(uint8_t **aSelf);

extern void __Elements_ProtoSkipValue(uint8_t **aSelf, __Elements_ProtoReadType aType);

extern double __Elements_ProtoReadDouble(uint8_t **aSelf);

extern int32_t __Elements_ProtoReadFixed32(uint8_t **aSelf);

extern int64_t __Elements_ProtoReadFixed64(uint8_t **aSelf);

extern NSString *__Elements_ProtoReadString(uint8_t **aSelf);

extern uint8_t * /* dynamicarray */ __Elements_ProtoReadBytes(uint8_t **aSelf);

extern int32_t MAX(int32_t x, int32_t y);

extern int64_t MAX(int64_t x, int64_t y);

extern uint32_t MAX(uint32_t x, uint32_t y);

extern uint64_t MAX(uint64_t x, uint64_t y);

extern uint32_t MAX(int32_t x, uint32_t y);

extern uint32_t MAX(uint32_t x, int32_t y);

extern uint64_t MAX(int64_t x, uint64_t y);

extern uint64_t MAX(uint64_t x, int64_t y);

extern float MAX(float x, float y);

extern double MAX(double x, double y);

extern int32_t MIN(int32_t x, int32_t y);

extern int64_t MIN(int64_t x, int64_t y);

extern uint32_t MIN(uint32_t x, uint32_t y);

extern uint64_t MIN(uint64_t x, uint64_t y);

extern int32_t MIN(int32_t x, uint32_t y);

extern int32_t MIN(uint32_t x, int32_t y);

extern int64_t MIN(int64_t x, uint64_t y);

extern int64_t MIN(uint64_t x, int64_t y);

extern float MIN(float x, float y);

extern double MIN(double x, double y);

extern int32_t ABS(int32_t x);

extern int64_t ABS(int64_t x);

extern double ABS(double x);

extern uint16_t ntohs(uint16_t n);

extern uint16_t htons(uint16_t n);

extern uint32_t ntohl(uint32_t n);

extern uint32_t htonl(uint32_t n);

extern uint32_t _OSSwapInt32(uint32_t a);

extern uint16_t _OSSwapInt16(uint16_t a);

extern uint64_t _OSSwapInt64(uint64_t a);

extern BOOL __builtin_constant_p(id o);

extern double op_Pow(double a, double b);

extern int64_t op_Pow(int64_t a, int64_t b);

extern int32_t op_Pow(int32_t a, int32_t b);

